### ISSUE TITLE
TypeError with function `hasLength()`

### ISSUE THREAD

**Issue by TamasHugyak** [unitjs/unit.js#14]
Hi,

I am using the `hasLength()` function to check the length of an array. Here is my code:

```
var result = [ 
    [ 'dog', 'boy', 'father', 'city', 'mother' ],
    [ 'dog', 'boy', 'father', 'work', 'city', 'mother' ],
    [ 'dog', 'boy', 'mother' ] 
];

unitjs.array(result).hasLength(1);
```

By the running I get this error message:

```
   TypeError: Cannot read property 'actual' of undefined
      at fail (node_modules/unit.js/src/helpers.js:194:48)
      at ArrayAsserter.hasLength (node_modules/unit.js/src/assertions.js:624:11)
      at Context.<anonymous> (app-hybrid-gui/server/tests/routing/two-table.js:103:7)
```

My unit.js's version is: 2.0.0

**Comment by neverfox** [comment]
Same.
