### ISSUE TITLE
unit tests fail on master

### ISSUE THREAD

**Issue by mattbishop** [unitjs/unit.js#19]
When I run the unit tests I get two failures (the other 418 pass):

```1) Asserter date() Assertions of date() notMatch(expected):
     AssertionError: Missing expected exception
      at UnitJS.fail (src/helpers.js:204:5)
      at new ExceptionAsserter (src/asserters/exception.js:153:9)
      at DateAsserter.fs.readdirSync.forEach.module.exports.(anonymous function) [as exception] (src/asserters.js:27:14)
      at Context.<anonymous> (test/src/asserters/date.js:201:10)

  2) Asserter date() Assertions of date() isNotValid(expected):
     AssertionError: Missing expected exception
      at UnitJS.fail (src/helpers.js:204:5)
      at new ExceptionAsserter (src/asserters/exception.js:153:9)
      at DateAsserter.fs.readdirSync.forEach.module.exports.(anonymous function) [as exception] (src/asserters.js:27:14)
      at Context.<anonymous> (test/src/asserters/date.js:231:10)
```

What is odd about these tests is that they are expecting a failure when in fact the assertion is correct.  For instance, the first failed example tests `test.date(date).notMatch(/02/)` for `new Date('2010, 5, 20')` but expects a failure result. When I debug this statement it does not throw an AssertionError as expected. If I change the test at line 202 to `test.date(date).notMatch(/2010/)` it fails, throws an AssertionError and the test passes.

The same is true for the second failing example.

**Comment by Nicolab** [comment]
Hello,

I can't reproduce, all tests pass.
What is the environment (browser or Node) that runs the tests? 

Thanks

**Comment by mattbishop** [comment]
node 6.9.1, os x 10.12.2

**Comment by mattbishop** [comment]
What happens if you change your local test to match mine? Does it still pass or fail?
